<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->insert([
            [
                'abbr' => 'en',
                'name' => 'English',
                'direction' => 'LTR',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ar',
                'name' => 'Arabic',
                'direction' => 'RTL',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'bs',
                'name' => 'Bosnian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'bg',
                'name' => 'Bulgarian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ca',
                'name' => 'Catalan',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ca',
                'name' => 'Catalan',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'cs',
                'name' => 'Czech',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'da',
                'name' => 'Danish',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'de',
                'name' => 'German',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'el',
                'name' => 'Greek',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'et',
                'name' => 'Estonian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'fi',
                'name' => 'Finnish',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'fr',
                'name' => 'French',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'he',
                'name' => 'Hebrew',
                'direction' => 'RTL',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'hi',
                'name' => 'Hindi',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'hu',
                'name' => 'Hungarian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'id',
                'name' => 'Indonesian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'it',
                'name' => 'Italian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ja',
                'name' => 'Japanese',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'kk',
                'name' => 'Kazakh',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ko',
                'name' => 'Korean',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'lt',
                'name' => 'Lithuanian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'lv',
                'name' => 'Latvian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'mg',
                'name' => 'Malagasy',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'mk',
                'name' => 'Macedonian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ms',
                'name' => 'Malay',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'nb',
                'name' => 'Norwegian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'nl',
                'name' => 'Dutch',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'fa',
                'name' => 'Persian',
                'direction' => 'RTL',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'pl',
                'name' => 'Polish ',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'pt',
                'name' => 'Portuguese',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ro',
                'name' => 'Romanian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ru',
                'name' => 'Russian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'zh',
                'name' => 'Chinese',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'sr',
                'name' => 'Serbian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'sk',
                'name' => 'Slovak',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'es',
                'name' => 'Spanish',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'sv',
                'name' => 'Swedish',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'tl',
                'name' => 'Tagalog',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'th',
                'name' => 'Thai',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'tr',
                'name' => 'Turkish',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'uk',
                'name' => 'Ukrainian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'vi',
                'name' => 'Vietnamese',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'af',
                'name' => 'Afrikaans',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'az',
                'name' => 'Azerbaijani',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'bn',
                'name' => 'Bengali',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'cy',
                'name' => 'Welsh',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'hy',
                'name' => 'Armenian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ka',
                'name' => 'Georgian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ku',
                'name' => 'Kurdish',
                'direction' => 'RTL',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ka',
                'name' => 'Georgian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'mn',
                'name' => 'Mongolian',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'abbr' => 'ne',
                'name' => 'Nepali',
                'direction' => 'LTR',
                'status' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
